config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'
  post 'welcome/home'

  get 'welcome/about'

  get 'welcome/doc'
  get 'welcome/cktest'

  get 'utils/toggleAdmin'
  get 'utils/toggleRantsOnly'
  get 'utils/modal_image_resize'
  get 'welcome/toggleRantsOnly'
  get 'welcome/myCommentsOnly'
  get 'welcome/filtersOff'
  get 'comments/show_admin'

#  get 'commentable_contents/show_by_type'
  get 'commentable_contents/show_by_id'
  get "comments/new_comment/:id" => 'comments#new_comment', :as => :new_comment
  get "comments/change_status/:id" => 'comments#change_status', :as => :change_status
  get "user_options/toggle_subscription/:id" => 'user_options#toggle_subscription', :as => :toggle_subscription
  get "user_options/toggle_email/:id" => 'user_options#toggle_email', :as => :toggle_email
  get "user_options/send_test_push_notification" => 'user_options#send_test_push_notification', :as => :send_test_push_notification
  get "user_options/send_test_email_notification" => 'user_options#send_test_email_notification', :as => :send_test_email_notification
  resources :comment_reviews
  resources :comments
  resources :commentable_contents do
  	resource :comments
  end
  resources :user_options
#  resources :rogues, controller: 'commentable_contents', type: 'Rogue' 
#  resources :current_events , controller: 'commentable_contents', type: 'CurrentEvent' 
#  resources :truth_in_media , controller: 'commentable_contents', type: 'TruthInMedia' 
 # get :currentevent , controller: 'commentable_contents', action: 'create', type: 'CurrentEvent' 
  devise_for :users, :controllers => { :sessions => "sessions" } # etc
  devise_for :admins, :controllers => { :sessions => "sessions" } # etc
#  devise_for :users, controllers: { passwords: 'passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
end

app/views/shared/content/_show_by_type.html.erb
   
<%#@type = local_assigns[:type] %>
<%#@title = local_assigns[:title] %>
<%
my_debug("title: #{@title} rants_only: #{@rants_only}  commentable_contents: #{@commentable_contents.class.name} #{@commentable_contents.class.ancestors}")
%>

<% 
	# loop through the collection of commentable_contents, filtering them to show only one type.
	# Each type is displayed in its own scrollable column, along with its comments.
	# the select statement blows up if contents are nil, so check for nil first.
%>
<% if ! @commentable_contents.nil? %>
  <% @commentable_contents.order(publish_dt: :desc).each do |cc|  %>
	<%= render partial: "shared/content/table_content_row", locals: { cc: cc} %>
  <%end #end commentable_contents select%>
 <%end #end if commentable_contents nil%>

app/views/shared/content/_table_comment_row.html.erb
<%
 @rants_only = session[:rants_only]
 @author_only = session[:mycomments_only]
 show_cc = true
 if @rants_only
  show_cc = ["RANT"].include?(c.review_status)  
 else
  show_cc = ["REJK","RANT"].exclude?(c.review_status)
 end 

 if( @author_only and show_cc)
  show_cc = ((user_signed_in? and c.user_id == current_user.id) or admin_on?) 
 end
  userName = ""
          if c.user.alias.start_with?("user_alias_") 
            userName = c.user.email.split('@')[0] 
          else 
            userName = c.user.alias 
          end 

 return  if ! show_cc 
%>
<div class="m-3 comment-row" id="comment-row-<%=c.id%>">
   <figure class="media user-icon">
       <% 
          if c.user.avatar? 
       %>
       <%= link_to image_tag(c.user.avatar.url(:thumb)),controller: "utils", action: "modal_image_resize", remote: true, image_name: c.user.avatar.url,image_title: userName, "data-turbolinks" => false  %> 
       <% else %>
         <%=  image_tag( asset_path('fallback/thumb_DefaultPerson.png')) %>
        <%  end %>

       <figcaption class="media-body">
       	
       <p class="figcap">  
        <%=
        userName
        %>
       <br/>
       <%= c.created_at %> 
     </p>
      <!--
      if the comment belongs to the current user and is not a rant, show the dropdown for edit/review actions.
      Allow review messages any time, however do not allow editing after the comment has been published (i.e. APPR)
      -->
       <% if ((user_signed_in? and c.user_id == current_user.id)  and c.review_status != "RANT") or admin_on? %>
        <div class="dropdown">
         <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
          Action 
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to "Edit", edit_comment_path(c.id),"data-turbolinks" => false ,  remote: true,class: "dropdown-item" if c.review_status != 'APPR' or admin_on? %>
          <%= link_to "Review", comment_reviews_path(comment_id: c.id),"data-turbolinks" => false , class: "dropdown-item"  %>
        </div>
        </div>
      <%end%>
       </figcaption>
	</figure>
	<div class="comment-text" id="comment-text<%=c.id%>">
  <!-- Only show the comment text if it approved, or it is a rand and RANTS filter is on, or user is an administrator
  -->
	<% if c.review_status == 'APPR' || (c.review_status == 'RANT' && @rants_only) || admin_on? %>
  <%= raw c.comment_text %>
  <% else %>
  <%=  I18n.t "comment_review_status.#{c.review_status}.name" %>
  <% end %>
  <hr>
	</div>
</div>
<!--
 <%#= link_to "Edit", new_comment_path(c.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} if user_signed_in? and  c.user_id == current_user.id  %>
 <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
           <ul class="enlarge">
            <li><img src=<%#=c.user.avatar.url(:thumb)%> "/><span><img src=<%#=c.user.avatar.url%> top="0px" left="0px" height="auto" width="100%" /> </span></li>
          </ul>
       <img src=<%=c.user.avatar.url%> class="grow"" />
      <%#=    image_tag(c.user.avatar.url, class: "imgfull", size: "500x600" )%>
      <%#=    image_tag(c.user.avatar.url,{class="img-responsive" alt="image" width="100%" height="auto"})  %>
-->
<!--  Do not remove this file.  Even though it is empty of content, it is needed because of
  the way Rails does ajax requests.   The file named modal_image_resize.js.erb  must have 
  this file as a companion that is called after the js is executed
-->

app/views/shared/content/_table_content_row.erb
<%# my_debug "In _table_content_row.erb partial, " + request.path 
	# show the commentable_content (CC) topic using bootstraps card formatting
	# if the content title is clicked on, show only that content (show_by_id)
	# show_by_id will show the full text, which is otherwise truncated to 100 char.
	# A user can add a comment, but only an admin can edit the CC content.
%>
 	<% 
 	if cc.publish_dt.nil? and !admin_on?
 		return
 	end
 	%>
	<div class="container">
  	<div class="row">
  	    <div class="col-sm-3 mx-3">
			<%= link_to image_tag(cc.picture.url, class:"img-thumbnail"),controller: "utils", action: "modal_image_resize", remote: true, image_name: cc.picture.url,image_title: cc.title, "data-turbolinks" => false  %> 
	  	<p class="author-line"> Updated <%= cc.updated_at.strftime("%Y-%m-%d %H:%M") %> </p>
			<%#=image_tag(cc.picture.url(:thumb)) %>
  		<!--div class="col-8 col-sm-6 text-justify" -->
		</div> 
  	    <div class="col-sm-6 mx-3">
  	    	<div class="content-title-author">
		  	<h3>
				<%= link_to cc.title , controller: "commentable_contents", action: "show_by_id", id: cc.id %>
			</h3>
		  	<% if cc.publish_dt.nil? %>
		  	<span class="inline-el-attn"> Not Published. Unavailable for other users to view </span>
		  	<%else%>
		  	<span class="author-line"> Published by </span> 
		  	<span class="author"> <%= User.find(cc.created_by_id).alias %> </span>
		  	<span class="author-line">  on <%= cc.publish_dt.strftime("%Y-%m-%d %H:%M") %> </span>
		  	<%end%>
			<!--p class="d-none d-sm-flex"-->
		  </div>
			<br>
			<p class="d-sm-flex">
				<%= cc.extract %> 
			</p>
		  	<hr class='user_edit_hr'>
		  	<!--div class="content-hr-100" </div-->
			<p>
				<!-- sanitize removes unwanted tags -->
				<%if action_name == "show_by_id" %>
					<%= sanitize cc.content %>
					<%#= raw cc.content.force_encoding("UTF-8") %>
				<%#else%>
					<%#= sanitize cc.content[0,100] + "..." %>
				<%end%>
			</p>
  		<!--div class="col-sm-3"> </div-->
  		</div>
  		</div>
	<%if action_name == "show_by_id" %>
     <div class="row text-muted">
  		<div class="col-sm-8"> 
		<hr>
	    <% if user_signed_in? %>	
		<%= link_to 'Add Comment',  new_commentable_content_comments_path(commentable_content_id: cc.id), remote: true, "data-turbolinks" => false , class: "card-link" %>
		<%else%>
		<%= link_to 'Sign in to Add Comment',  new_user_session_path, class: "nav-link" %>
		<%end%>
		<%= link_to 'Edit Article',  edit_commentable_content_path(cc.id),"data-turbolinks" => false, class: "card-link" if admin_signed_in? and admin_on? %>
	  	<%#= social_share_button_tag(cc.title,:allow_sites => %w(twitter facebook email reddit )) %>
	  	<%#= social_share_button_tag(cc.title,:allow_sites => %w(twitter facebook google_plus google_bookmark delicious pinterest email linkedin reddit )) %>
	 </div>
	 </div>
	 <% end #action_name = show_by_id %>
	</div>

	
	 <% if false #comment out%>
	 <% end #comment out%>

app/views/shared/content/_table_content_row_card.erb
<% my_debug "In _table_content_row.erb partial, " + request.path 
	# show the commentable_content (CC) topic using bootstraps card formatting
	# if the content title is clicked on, show only that content (show_by_id)
	# show_by_id will show the full text, which is otherwise truncated to 100 char.
	# A user can add a comment, but only an admin can edit the CC content.
%>
  	<div class="card flex-row flex-wrap">
		<div class="card-header border-0">
			<%= link_to image_tag(cc.picture.url, width: 200,class: "img-flex"),controller: "utils", action: "modal_image_resize", remote: true, image_name: cc.picture.url,image_title: cc.title, "data-turbolinks" => false  %> 
  			<%#=image_tag(cc.picture.url(:thumb)) %>
  		</div>	
	 <div class="card-block px-2">
	  	<h5 class="card-title">
			<%= link_to cc.title , controller: "commentable_contents", title: @title,action: "show_by_id", id: cc.id %>
		</h5>
		<p class="card-text">
			<%= cc.extract %> 
		</p>
	  	<p class="author-line"> Created by <%= User.find(cc.created_by_id).alias + " on " + cc.created_at.strftime("%Y-%m-%d %H:%M") %> </p>
		<hr>
		<p class="card-text">
			<!-- sanitize removes unwanted tags -->
			<%if action_name == "show_by_id" %>
				<%= sanitize cc.content %>
				<%#= raw cc.content.force_encoding("UTF-8") %>
			<%#else%>
				<%#= sanitize cc.content[0,100] + "..." %>
			<%end%>
		</p>
	 </div>
     <div class="w-100"></div>
     <div class="card-footer w-100 text-muted">
	  	<p class="author-line"> Updated <%= cc.updated_at.strftime("%Y-%m-%d %H:%M") %> </p>
		<%= link_to 'Add Comment',  new_commentable_content_comments_path(commentable_content_id: cc.id), remote: true, "data-turbolinks" => false , class: "card-link" if user_signed_in? %>
		<%= link_to 'Edit Content',  edit_commentable_content_path(cc.id),"data-turbolinks" => false, class: "card-link" if admin_signed_in? and admin_on? %>
	  	<%= social_share_button_tag(cc.title,:allow_sites => %w(twitter facebook email reddit )) %>
	  	<%#= social_share_button_tag(cc.title,:allow_sites => %w(twitter facebook google_plus google_bookmark delicious pinterest email linkedin reddit )) %>
	 </div>
	</div>

app/views/shared/content/_table_thead.html.erb
  <thead>
    <tr>
      <th>Icon</th>
      <th colspan="3">Extract</th>
    </tr>
  </thead>