config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'
  post 'welcome/home'

  get 'welcome/about'

  get 'welcome/doc'
  get 'welcome/cktest'

  get 'utils/toggleAdmin'
  get 'utils/toggleRantsOnly'
  get 'utils/modal_image_resize'
  get 'welcome/toggleRantsOnly'
  get 'welcome/myCommentsOnly'
  get 'welcome/filtersOff'
  get 'comments/show_admin'

#  get 'commentable_contents/show_by_type'
  get 'commentable_contents/show_by_id'
  get "comments/new_comment/:id" => 'comments#new_comment', :as => :new_comment
  get "comments/change_status/:id" => 'comments#change_status', :as => :change_status
  get "user_options/toggle_subscription/:id" => 'user_options#toggle_subscription', :as => :toggle_subscription
  get "user_options/toggle_email/:id" => 'user_options#toggle_email', :as => :toggle_email
  get "user_options/send_test_push_notification" => 'user_options#send_test_push_notification', :as => :send_test_push_notification
  get "user_options/send_test_email_notification" => 'user_options#send_test_email_notification', :as => :send_test_email_notification
  resources :comment_reviews
  resources :comments
  resources :commentable_contents do
  	resource :comments
  end
  resources :user_options
#  resources :rogues, controller: 'commentable_contents', type: 'Rogue' 
#  resources :current_events , controller: 'commentable_contents', type: 'CurrentEvent' 
#  resources :truth_in_media , controller: 'commentable_contents', type: 'TruthInMedia' 
 # get :currentevent , controller: 'commentable_contents', action: 'create', type: 'CurrentEvent' 
  devise_for :users, :controllers => { :sessions => "sessions" } # etc
  devise_for :admins, :controllers => { :sessions => "sessions" } # etc
#  devise_for :users, controllers: { passwords: 'passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
end

app/models/user_option.rb
class UserOption < ApplicationRecord
  belongs_to :user
end

app/controllers/user_options_controller.rb
class UserOptionsController < ApplicationController
  before_action :authenticate_admin!,only: [:index]
  before_action :authenticate_user! , except: [:index]
  before_action :set_user_option, only: [:show, :edit, :update, :destroy,:toggle_subscription,:toggle_email,:send_test_push_notification]
  before_action :show_params, only: [:send_test_push_notification]
  before_action :set_delivery_method
  #
  #send_test_push_notification is an ajax call, however in the (hopefully rare) event that
  #Webpush returns an error, the edit view nees to be re-rendered entirely, in order to kick off
  #the javascript 'checkBrowserSupport' function, which then resets some classes on the user_options
  #form.  Thereby, it gets a little tricky, needing to return ajax when successful, but do
  #a full re-render of the view if it errors.  test_push_notification.js.erb does a page refresh to
  #accomplish this.
  #
  rescue_from  Webpush::ResponseError , with: :handle_webpush_error 
  # GET /user_options
  # GET /user_options.json
  def index
    @user_options = UserOption.all
  end

  # GET /user_options/1
  # GET /user_options/1.json
  def show
  end

  # GET /user_options/new
  def new
    @user_option = UserOption.new
  end

  # GET /user_options/1/edit
  def edit
    @user_option
  end
  def toggle_email
    if !(params.dig(:user_option,:email).nil?)
      @user_option.email = params.dig(:user_option,:email)
    else
      @user_option.email = false
    end      
    respond_to do |format|
     format.js { render 'toggle_email.js.erb', layout: false }
    end
  end

  def toggle_subscription
    @user_option
    #
    #A lot of s**t to go through just to get a true/false log value !!
    #
    Rails.logger.info "user_option.notification : " +  (!( params.dig(:user_option,:notification).nil?)).to_s  
    if !(params.dig(:user_option,:notification).nil?)
      @user_option.notification = params.dig(:user_option,:notification)
    else
      @user_option.notification = false
    end      
    respond_to do |format|
     format.js { render 'toggle_subscription.js.erb', layout: false }
     #format.js { render 'toggle_subscription.js.erb' }
     #format.js
    end
  end

  def send_test_email_notification
    @article = CommentableContent.last
    @user = User.find(params[:user_id])
  #  UserMailer.with(user: @user,article: @article).new_article(@delivery_method)
    UserMailer.with(user: @user,article: @article).new_article.deliver_now
    respond_to do |format|
       format.js
     end
  end
  def send_test_push_notification
    #required:  subscription, title, 
    #optional:  article(CommentableContent object)
    #          , action, icon
    @user_option
    @webpush_err = nil
    messaging = WebPushNotification.new({
     subscription: params[:subscription],
            title: 'New Content at Whodabudda' ,
            article: CommentableContent.last
      })
    messaging.call
#    rescue Webpush::ResponseError => e
#      Rails.logger.info e[:body][:code]

    respond_to do |format|
#       format.js { flash[:notice] =  "Notification was sent..." }
       format.js {}
     end

      #head :ok
  end


  # POST /user_options
  # POST /user_options.json
  def create
    @user_option = UserOption.new(user_option_params)

    respond_to do |format|
      if @user_option.save
        format.html { redirect_to :root, notice: 'User option was successfully created.' }
        format.json { render :show, status: :created, location: @user_option }
      else
        format.html { render :new }
        format.json { render json: @user_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_options/1
  # PATCH/PUT /user_options/1.json
  def update
    respond_to do |format|
      if @user_option.update(user_option_params)
        format.html { redirect_to :root, notice: 'User option was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_option }
      else
        format.html { render :edit }
        format.json { render json: @user_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_options/1
  # DELETE /user_options/1.json
  def destroy
    @user_option.destroy
    respond_to do |format|
      format.html { redirect_to user_options_url, notice: 'User option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #deliver_now is good for development, where deliver_later might fail (see rails doc)
    #This creates some discomfort in that behaviour can be different between environments
    def set_delivery_method
        @delivery_method = (Rails.env == "production" ? 'deliver_later' : 'deliver_now')
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_user_option
      @user_option = UserOption.find_by(user_id: current_user.id, browser: browser.name)
      if @user_option.nil?
        @user_option = UserOption.new(user_id: current_user.id , browser: browser.name)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_option_params
      params.require(:user_option).permit(:user_id, :email, :sms, :notification, :subscription,:browser)
    end
    def show_params
      Rails.logger.info "Displaying params: #{params} "

    end
    def handle_webpush_error(e)
      #regex to get all the characters between brackets {}.
      #Warning: This could be a problem if Zaru::Webpush ever changes the format of its error string.
      #Currently, the string error from Webpush has only one set of {}, whith the enclosed content
      #in a hash format.
      tmp = e.to_s[/{(.+)}/, 1] 
      #now parse into hash format, adding enclosing {} back in
      @webpush_err = JSON.parse("{#{tmp}}") 
      #
      #wipe out the subscription, since it failed.
      #TODO: check return codes; we probably only want to reset the subscription if it is actually 
      #expired.  If other errors, like too busy or content too long, subscription is actually ok 
      #and we need to take different action.
      #
      @user_option.subscription = ''
      @user_option.save

      Rails.logger.info "#{controller_name}:#{action_name} webpush code: #{@webpush_err["code"]} message: #{@webpush_err["message"]} "
     respond_to do |format|
      #format.js { redirect_to edit_user_option_path(@user_option), notice: @webpush_err["message"] }
       format.js { render 'send_test_push_notification.js.erb', layout: false }
     end

#      respond_to do |format| format.html { redirect_to edit_user_option_path, notice: "Unable to send notification #{e.message}" } end
    end

    def fetch_subscription
     # encoded_subscription = session.fetch(:subscription) do
     #   raise "Cannot create notification: no :subscription in params or session"
     # end
      #params.permit(:subscription)
      #encoded_subscription = params(:subscription)
      #JSON.parse(Base64.urlsafe_decode64(encoded_subscription)).with_indifferent_access
    end
end

app/helpers/user_options_helper.rb
module UserOptionsHelper
end

app/views/user_options/_form.html.erb
<%= form_with model: @user_option, local: true, id: "user_options_form" do |form| %>
    <div id="webpush_test_error">
    </div>
  <% if user_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_option.errors.count, "error") %> prohibited this user_option from being saved:</h2>

      <ul>
      <% user_option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <p class="field-note">
  Note: These options are currently used only for new content, i.e. if you enable the box, you will receive a notification in either email or a browser form <i><b>only</b></i> when a new Article is posted.  These settings do not affect how we communicaate about reviews or changes in the status of your comments.  We hope to provide more fine-grained communication preferences in the near future.
</p>
 
  <% my_debug("notification value: #{@user_option.notification}") %>
  <% my_debug("notification value: #{@user_option.subscription}") %>
  <div class="field" hidden="true">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field email-checkbox">
    <%= form.label :email %>
    <%#= form.check_box :email %>
    <%= form.check_box :email,:id => 'email-checkbox', data: { :url => url_for(:controller => "user_options", :action => "toggle_email", :id => @user_option.user_id ), remote: true, turbolinks: false,  autocomplete: "off"} %><span></span> 
  </div>
  <div class="field">
  </div>

  <div class="field" hidden="true" >
    <%= form.label :sms %>
    <%= form.check_box :sms %>
  </div>

  <div class="field webpush-checkbox">
    <%= form.label :notification %>
    <%#= form.check_box :notification, :onevent => 'AjaxEventFunction', :id => 'webpush-checkbox', data: { url: edit_user_option_path, remote: true, method: :get, action: "jquery:ajax:beforeSend->edit"} %> 
    <%= form.check_box :notification,:id => 'webpush-checkbox', data: { :url => url_for(:controller => "user_options", :action => "toggle_subscription", :id => @user_option.user_id ), remote: true, turbolinks: false,  autocomplete: "off"} %><span></span> 
  </div>
  <div class="field">
    <span class="subscription_message"></span>
    <%= form.label :subscription , :hidden => true %>
    <%= form.text_area :subscription , :id => 'webpush-subscription', :hidden => true  %>
  </div>
  <div class="field">
    <span class="browser"></span>
    <%= form.label :browser, :hidden => true  %>
    <%= form.text_area :browser , value: browser.name, :id => 'webpush-browser', :hidden => true %>
  </div>

  <div class="actions" >
    <%= form.submit %>
  </div>
    <%# hidden_field_tag "webpush[notification]", false %>

<% end %>
<%#=javascript_include_tag 'user_options_form' %>

app/views/user_options/_push_test.html.erb
<% my_debug("subscription length: #{ @user_option.subscription.length}, notification: #{@user_option.notification}") %>
<% if @user_option.notification && @user_option.subscription.length > 100 %>
<%= link_to 'Send Test Notification', :controller => "user_options", :action => "send_push_notification", params: {:id => @user_option.id, :user_id => @user_option.user_id,:subscription => @user_option.subscription},remote: true %> 
<% end %>

app/views/user_options/edit.html.erb
<h2>User Option</h2>

<% comment do %>
<p>Device Info: <%= browser.device %> </p>
<p>Device name: <%= browser.device.name %> </p>
<p>Device Mobile?: <%= browser.device.mobile? %> </p>
<p>Browser Name: <%= browser.name %> </p>
<%comment end %>

<%= render 'form', user_option: @user_option %>
<%#= render 'push_test', user_option: @user_option %>
<% my_debug("subscription length: #{ @user_option.subscription.length}, notification: #{@user_option.notification}") unless @user_option.subscription.nil?  %>
<br>
<!-- 
The link_to helper takes 4 parameters, (name, url with options, html options, block)
any html options must be added as the 3rd parameter (array index #2)
-->
<% if @user_option.notification && @user_option.subscription.length > 100 %>
<div class='push_test'>
<%= link_to 'Send Test Web Notification',  send_test_push_notification_path( params: { :id => @user_option.id, :user_id => @user_option.user_id,:subscription => @user_option.subscription}), remote: true , class: "test"%> 
</div>
<% end %>
<% if @user_option.email %>
<div class='email_test'>
<%= link_to 'Send Test Email Notification',  send_test_email_notification_path( params: { :id => @user_option.id, :user_id => @user_option.user_id}), remote: true , class: "test"%> 
</div>
<% end %>

<%= link_to 'Show', @user_option if admin_signed_in? and admin_on?%> 
<%= link_to 'Back', welcome_home_path %>

<script type="module">
  //checkBrowserSupport is exported and made global with the expose-loader module
  var vapidPublic = "<%=ENV['VAPID_PUBLIC'] %>";
  console.log('vapid: ', vapidPublic);
  checkBrowserSupport.checkBrowserSupport(vapidPublic);   // to show messages on if push notification is available
</script>

<!-- <script type="text/javascript">
	alert("Im in the edit");
document.addEventListener('ajax:before', function(event) {
  var detail = event.detail;
  var data = detail[0], status = detail[1], xhr = detail[2];
  console.log('ajax:before non-jquery  input', data);
  alert('ajax:before non-jquery input', detail,xhr);
});
document.addEventListener('ajax:beforesend', function(event) {
  var detail = event.detail;
  var data = detail[0], status = detail[1], xhr = detail[2];
  console.log('ajax:beforesend non-jquery  input', detail,xhr);
  alert('ajax:beforesend non-jquery input', detail,xhr);
});
document.addEventListener('ajax:send', function(event) {
  var detail = event.detail;
  var data = detail[0], status = detail[1], xhr = detail[2];
  console.log('ajax:send non-jquery  input', detail,xhr);
  alert('ajax:send non-jquery input', detail,xhr);
});
document.addEventListener('ajax:success', function(event) {
  var detail = event.detail;
  var data = detail[0], status = detail[1], xhr = detail[2];
  console.log('ajax:success non-jquery  input', detail,xhr);
  alert('ajax:success non-jquery input', detail,xhr);
});
document.addEventListener('ajax:complete', function(event) {
  var detail = event.detail;
  var data = detail[0], status = detail[1], xhr = detail[2];
  console.log('ajax:complete non-jquery  input', detail,xhr);
  alert('ajax:complete non-jquery input', detail,xhr);
});
</script>
 -->

app/views/user_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Options</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Email</th>
      <th>Sms</th>
      <th>Notification</th>
      <th>Subscription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_options.each do |user_option| %>
      <tr>
        <td><%= user_option.user %></td>
        <td><%= user_option.email %></td>
        <td><%= user_option.sms %></td>
        <td><%= user_option.notification %></td>
        <td><%= user_option.subscription %></td>
        <td><%= link_to 'Show', user_option %></td>
        <td><%= link_to 'Edit', edit_user_option_path(user_option) %></td>
        <td><%= link_to 'Destroy', user_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Option', new_user_option_path %>

app/views/user_options/new.html.erb
<h1>New User Option</h1>

<%= render 'form', user_option: @user_option %>

<%= link_to 'Back', user_options_path %>

app/views/user_options/send_test_push_notification.js.erb
<% if ! @webpush_err.nil? %>
	document.location.reload()
	var err_msg = " <%= j @webpush_err["message"] %> "
	//checkBrowserSupport()
	$('#webpush_test_error').removeClass().addClass('alert alert-danger');
	$('#webpush_test_error').text("Not able to send push:" + err_msg);
	//document.getElementById('webpush_test_error').textContent = "Not able to send push:" + err_msg;
<% else %>
	$("#webpush_test_error").html("<%= flash.now[:notice] =  "Notification was sent..."  %>").removeClass().addClass('alert alert-success');
<% end %>
// document.getElementById("webpush_test_error").value =

app/views/user_options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_option.user %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_option.email %>
</p>

<p>
  <strong>Sms:</strong>
  <%= @user_option.sms %>
</p>

<p>
  <strong>Notification:</strong>
  <%= @user_option.notification %>
</p>

<p>
  <strong>Subscription:</strong>
  <%= @user_option.subscription %>
</p>

<%= link_to 'Edit', edit_user_option_path(@user_option) %> |
<%= link_to 'Back', user_options_path %>

app/views/user_options/toggle_email.js.erb
   console.log("entered toggle_email.js.erb")
   var checkbox = <%=@user_option.email %>;
   console.log("toggle_email.js.erb - checkbox: ", checkbox )

   $('.email_test').attr("hidden" , !checkbox)

app/views/user_options/toggle_subscription.js.erb
   console.log("entered toggle_subscription.js.erb")
   var checkbox = <%=@user_option.notification %>;
   var current_subscription = "<%= @user_option.subscription %>";
   console.log("toggle_subscription.js.erb - checkbox: ", checkbox )
   console.log("toggle_subscription.js.erb - subscription: ", current_subscription )

   $('.push_test').attr("hidden" , !checkbox)
   checkBrowserSupport.checkBrowserSupport()
   if(!checkbox) {
      $('.subscription_message').text('Save your options to stop receiving notifications').addClass('notifications-problem').removeClass('checked');
   }
   /*
   if(checkbox) {
      //curJSObject = JSON.parse(current_subscription);
      if (checkNotification()) {
        setSubscriptionValues()
      }
   }
   else {
      $('.subscription_message').text('Save your options to stop receiving notifications').addClass('notifications-problem').removeClass('checked');
   }
  */ 
  