config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'
  post 'welcome/home'

  get 'welcome/about'

  get 'welcome/doc'
  get 'welcome/cktest'

  get 'utils/toggleAdmin'
  get 'utils/toggleRantsOnly'
  get 'utils/modal_image_resize'
  get 'welcome/toggleRantsOnly'
  get 'welcome/myCommentsOnly'
  get 'welcome/filtersOff'
  get 'comments/show_admin'

#  get 'commentable_contents/show_by_type'
  get 'commentable_contents/show_by_id'
  get "comments/new_comment/:id" => 'comments#new_comment', :as => :new_comment
  get "comments/change_status/:id" => 'comments#change_status', :as => :change_status
  get "user_options/toggle_subscription/:id" => 'user_options#toggle_subscription', :as => :toggle_subscription
  get "user_options/toggle_email/:id" => 'user_options#toggle_email', :as => :toggle_email
  get "user_options/send_test_push_notification" => 'user_options#send_test_push_notification', :as => :send_test_push_notification
  get "user_options/send_test_email_notification" => 'user_options#send_test_email_notification', :as => :send_test_email_notification
  resources :comment_reviews
  resources :comments
  resources :commentable_contents do
  	resource :comments
  end
  resources :user_options
#  resources :rogues, controller: 'commentable_contents', type: 'Rogue' 
#  resources :current_events , controller: 'commentable_contents', type: 'CurrentEvent' 
#  resources :truth_in_media , controller: 'commentable_contents', type: 'TruthInMedia' 
 # get :currentevent , controller: 'commentable_contents', action: 'create', type: 'CurrentEvent' 
  devise_for :users, :controllers => { :sessions => "sessions" } # etc
  devise_for :admins, :controllers => { :sessions => "sessions" } # etc
#  devise_for :users, controllers: { passwords: 'passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
end

app/models/commentable_content.rb
class CommentableContent < ApplicationRecord
	validate :publish_dt_cannot_be_in_the_past
	mount_uploader :picture, PictureUploader
	#has_many :comments, as: :commentable
	has_many :comments, foreign_key: :commentable_id

  def publish_dt_cannot_be_in_the_past
    if publish_dt.present? && publish_dt_will_change! && publish_dt < Date.today - 15.minutes
      errors.add(:publish_dt, "can't be in the past. Update the publish date or remove it")
    end
  end

end

app/controllers/commentable_contents_controller.rb
class CommentableContentsController < ApplicationController
  before_action :authenticate_admin!, except: [:show_by_id,:index,:show]
  skip_before_action :authenticate_user!
  before_action :set_commentable_content, only: [:show_by_id,:edit, :update, :destroy, :show]
  #before_action :log_action
  around_action :set_current_user_timezone , only: [:create,:update,:show_by_id]
  # GET /commentable_contents
  # GET /commentable_contents.json
  def index
    @commentable_contents = CommentableContent.all
  end

  # GET /commentable_contents/1
  # GET /commentable_contents/1.json
  def show_by_id
    @commentable_contents  = CommentableContent.find(params[:id])
    if params[:title].nil?
      @title = @commentable_contents.title
    else
      @title = params[:title]
    end
  end

  # GET /commentable_contents/new
  def new
    @commentable_content = CommentableContent.new
  end

  # GET /commentable_contents/1/edit
  def edit
  end

  def show
  end

  def create
    @commentable_content = CommentableContent.new(commentable_content_params)
    if (!params[:publish].nil?) && params[:publish] == "1"
      @commentable_content.publish_dt = new DateTime.current
    end
    respond_to do |format|
      if @commentable_content.save
        @rtn_message = "Article was saved."
        cc = @commentable_content
        check_job(cc)
        format.html { redirect_to controller: "commentable_contents", title: cc.title, action: "show_by_id", id: cc.id , notice: @rtn_message }
        format.json { render :show, status: :created, location: @commentable_content }
      else
        format.html { render :new }
        format.json { render json: @commentable_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commentable_contents/1
  # PATCH/PUT /commentable_contents/1.json
  def update
    Rails.logger.info "Params[publish_dt class is: #{params[:publish].class} #{params[:publish]}"
    Rails.logger.info " "
    Rails.logger.info "fetched params are: #{commentable_content_params}"
    respond_to do |format|
        if (!params[:publish].nil?) && params[:publish][:publish] == "1"
          @commentable_content.publish_dt = DateTime.current
        end
      if @commentable_content.update(commentable_content_params)
        @rtn_message = "Article was saved."
        check_job(@commentable_content)
        if @commentable_content.publish_dt.nil?
          format.html { redirect_to edit_commentable_content_path, notice: @rtn_message }
        else
          format.html { redirect_to welcome_home_path , notice: @rtn_message }
        end
        format.json { render :show, status: :ok, location: @commentable_content }
      else
        format.html { render :edit }
        format.json { render json: @commentable_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commentable_contents/1
  # DELETE /commentable_contents/1.json
  def destroy
    @commentable_content.destroy
    respond_to do |format|
      format.html { redirect_to commentable_contents_url, notice: 'Commentable content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_commentable_content
     @commentable_content = CommentableContent.find(params[:id])
  end

  def check_job(article)
    #
    # Don't allow notifications for publishing past 10 days from now.
    # Past that, the author will probably forget its in the queue.
    # Publish dates in the past will not have notifications sent,
    # although it may problematic to allow changes to content after publishing.
    # We mostly have to trust authors not to abuse this privilege.
    # If the publish_dt is in the past, it will not be allowed to be changed in the view.
    # In the job, if the passed in publish_dt no longer matches the database publish_dt,
    # no notifications will be sent. This protects against sending multiple notifications
    # when the published date is changed within its 10 day window.
    # If the date is beyone 10 days, no notifications will be sent unless it is edited and
    # the publish_dt set to be within 10 days.
    Rails.logger.info "CommentableContentsController-check_job publish_dt #{article.publish_dt}"
    if  article.publish_dt.nil?
        @rtn_message += "No publish date set. Regular users cannot view the article"
    else
        @rtn_message += "Article is now published and available to users for viewing. Notifictions will be sent."
        PublishArticleJob.set(wait_until: article.publish_dt).perform_later( article.id, article.publish_dt)
    end
  end

  def commentable_content_params
      params.fetch(:commentable_content, {}).permit(:picture,:title, :extract,:content,:created_by_id,:modified_by_id,:id,:publish_dt)
  end
  def log_action
    Rails.logger.info "in: #{params[:controller]} : #{params[:action]}  for user: " + (user_signed_in? ? current_user.id.to_s : "no user logged in")
    Rails.logger.info "params are: #{params.inspect}"
    Rails.logger.info "fetched params are: #{commentable_content_params}"
  end

end

app/helpers/commentable_contents_helper.rb
module CommentableContentsHelper
end

app/views/commentable_contents/_form.html.erb
 <div class="container-fluid main-container">
    <div class="row flex-row-full align-items-start">
        <div class="col-xs-12 con-resize-full">

      <%#commentable_content.content.force_encoding("UTF-8") %>
      <%= form_for(commentable_content ) do |f| %>
        <% if commentable_content.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(commentable_content.errors.count, "error") %> prohibited this commentable_content from being saved:</h2>

            <ul>
            <% commentable_content.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
         <div class="field">
           <%= f.label :picture,  class: "custom-file-upload"  do %>
              <%= image_tag(commentable_content.picture.url(:thumb)) %>
             <span> <%= File.basename(commentable_content.picture.to_s) %> </span>
             <%= f.file_field :picture  %>
           <%end%>
           <%#= f.label :picture_url, File.basename(commentable_content.picture.to_s) %>
         </div>
        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title, :class => 'col-8' %>
        </div>
        <div class="field field-content-extract">
          <%= f.label :extract %><br>
          <%= f.text_area :extract, :class => 'col-8' %>
        </div>
        <div class="field">
          <%= f.label :content %><br>
          <%= f.text_area :content, :class => 'content-text-input editor',:id => 'editor' %>
        </div>
        <div class="field">
          <% if (! commentable_content.publish_dt.nil?) && commentable_content.publish_dt < Time.current %>
            <%= f.label :publish_dt %>
            <%= f.text_field :publish_dt, readonly: true%>
          <%else%>
            <%= f.label "Publish?" %>
             <%= check_box :publish, "publish" %>
             <p class="inline-el-attn">(The article is available to users, and cannot be revised after publishing.) </p> 
          <%end%>
        </div>
        <% if action_name == "new" %>
          <div class="field">
           <%= f.text_field :created_by_id, value: current_admin.id, hidden: true,readonly: true%>
         </div>
        <% end %>
        <div class="field">
          <%= f.text_field :modified_by_id, value: current_admin.id, hidden: true,readonly: true%>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%if false%>
<div class="field">
          <% if (! commentable_content.publish_dt.nil?) && commentable_content.publish_dt < Time.current
              @readonly_publish_dt = true
            else
              @readonly_publish_dt = false
            end
          %>
          <%= f.label :publish_dt %><br>
          <%= f.datetime_select :publish_dt, { :order => [:year,:month, :day, :hour, :minute],:start_year => Date.today.year,:end_year => Date.today.year + 1 } ,readonly: @readonly_publish_dt%>
        </div>
<%end%>

<script>
MyClassicEditor
    .create( document.querySelector( '#editor' ) )
    .then( editor => {
      //window.editor = editor;
      console.log (Array.from( editor.ui.componentFactory.names() ) );
    } )
    .catch( err => {
      console.error( err.stack );
    } );

//console.log (ClassicEditor.builtinPlugins.map( plugin => plugin.pluginName ));
</script>

app/views/commentable_contents/edit.html.erb
<h1>Editing Commentable Content</h1>
<%@commentable_content.content.force_encoding("UTF-8") %>
<%= render 'form', commentable_content: @commentable_content %>

<%= link_to 'Cancel', url_for( :back) %> 

app/views/commentable_contents/edit.js.erb
// Add the pblogModal title
$('#pblogModal h5').html("<i class='glyphicon glyphicon-pencil modal-title' id='pblogModalLongTitle'></i> Edit Article");
 
// Render the edit form
$('.modal-body-placeholder').html('<%= j render partial: "form", locals: { ismodal:  "true" } %>');

//////////////////////////////////////////////////////////////////////////////////
//Show the dynamic pblogModal
$('#pblogModal').modal("show");
 
// Set focus to the first element
$('#pblogModal').on('shown.bs.modal', function () {
	  $('.first_input').focus()
 });
 MyClassicEditor
    .create( document.querySelector( '#editor' ) )
    .then( editor => {
        console.log( editor );
    } )
    .catch( error => {
        console.error( error );
   } );

app/views/commentable_contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= @commentable_type %> </h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if ! @commentable_contents.nil?  %>
    <% @commentable_contents.each do |commentable_content| %>
      <tr>
        <td><%= link_to 'Show', commentable_content %></td>
        <td><%= link_to 'Edit', edit_commentable_content_path(commentable_content) %></td>
        <td><%= link_to 'Destroy', commentable_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% else %>
      <tr>
        <td>There is no content </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New ' + @commentable_type.to_s, new_polymorphic_path( @commentable_type.to_s.underscore) %>

app/views/commentable_contents/new.html.erb
<h1>New Commentable Content</h1>

<%= render 'form', commentable_content: @commentable_content %>

<%= link_to 'Back', commentable_contents_path %>

app/views/commentable_contents/show_by_id.html (copy).erb
      <div class="row">
          <div class="col-xs-12">
            <% if ! @commentable_contents.nil? %>
              <% cc = @commentable_contents %> 
              <%= render partial: "shared/content/table_content_row", locals: { cc: @commentable_contents, type:  @type , title: @title} %>
          </div>
      </div>
      <div class="row">
          <div class="col-2"> </div>
          <div class="col-7"> 
              <% cc.comments.each do |c| %>
                <%= render partial: "shared/content/table_comment_row", locals: { c: c, type:  @type , title: @title} %>
            </div>
          </div>
          <div class="col-3"> </div>
             <%end%>
          <p> <%#= session.inspect %> </p>
          <%end%>
      <%=render "shared/modal_dialog" %>


<%= link_to 'Edit', edit_commentable_content_path(@commentable_contents) if admin_signed_in? and admin_on? %>
<%= link_to 'Back', welcome_home_path %>

app/views/commentable_contents/show_by_id.html.erb
      <% if ! @commentable_contents.nil? %>
         <% cc = @commentable_contents %> 
           <%= render partial: "shared/content/table_content_row", locals: { cc: @commentable_contents, title: @title} %>
         <div id="comments_list"> <!-- comments_list needed in create.js.erb to append new comment -->
         <% cc.comments.each do |c| %>
             <%= render partial: "shared/content/table_comment_row", locals: { c: c, title: @title} %>
          <%end # end of comments loop %>
          </div>
          <p> <%#= session.inspect %> </p>
      <%end%>
      <%=render "shared/modal_dialog" %>


<%#= link_to 'Edit', edit_commentable_content_path(@commentable_contents) if admin_signed_in? and admin_on? %>
<%= link_to 'Back', welcome_home_path %>

app/views/commentable_contents/show_by_type.html.erb
    <div class="container-fluid main-container">
      <div class="row flex-row-full align-items-start">
      		<div class="col-xs-1 center">
            <%= link_to 'Back', welcome_home_path %>
      		</div>
      		<div class="col-xs-10 con-resize-full">
              <%= render partial: "shared/content/show_by_type", locals: { type:  @type , title: @title} %>
            <%#= render partial: "shared/commentable_list", locals: { type:  @type , title: @title, content_link_action: "show_by_id"} %>
      		</div>
      		<div class="col-xs-1">
      		</div>
      </div>
      <%=render "shared/modal_dialog" %>
    </div>

<!--
             <p> <%#= session.inspect %> </p>
      		<div class="col-xs-2">
      		</div>
-->