config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'
  post 'welcome/home'

  get 'welcome/about'

  get 'welcome/doc'
  get 'welcome/cktest'

  get 'utils/toggleAdmin'
  get 'utils/toggleRantsOnly'
  get 'utils/modal_image_resize'
  get 'welcome/toggleRantsOnly'
  get 'welcome/myCommentsOnly'
  get 'welcome/filtersOff'
  get 'comments/show_admin'

#  get 'commentable_contents/show_by_type'
  get 'commentable_contents/show_by_id'
  get "comments/new_comment/:id" => 'comments#new_comment', :as => :new_comment
  get "comments/change_status/:id" => 'comments#change_status', :as => :change_status
  get "user_options/toggle_subscription/:id" => 'user_options#toggle_subscription', :as => :toggle_subscription
  get "user_options/toggle_email/:id" => 'user_options#toggle_email', :as => :toggle_email
  get "user_options/send_test_push_notification" => 'user_options#send_test_push_notification', :as => :send_test_push_notification
  get "user_options/send_test_email_notification" => 'user_options#send_test_email_notification', :as => :send_test_email_notification
  resources :comment_reviews
  resources :comments
  resources :commentable_contents do
  	resource :comments
  end
  resources :user_options
#  resources :rogues, controller: 'commentable_contents', type: 'Rogue' 
#  resources :current_events , controller: 'commentable_contents', type: 'CurrentEvent' 
#  resources :truth_in_media , controller: 'commentable_contents', type: 'TruthInMedia' 
 # get :currentevent , controller: 'commentable_contents', action: 'create', type: 'CurrentEvent' 
  devise_for :users, :controllers => { :sessions => "sessions" } # etc
  devise_for :admins, :controllers => { :sessions => "sessions" } # etc
#  devise_for :users, controllers: { passwords: 'passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
end

app/views/shared/navbar/_navbar_default.html.erb
<!--
<nav class="navbar sticky-top navbar-toggleable-md navbar-expand-lg navbar-light bg-faded ">
-->
<nav class="navbar sticky-top navbar-expand-md bg-light navbar-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 <a class="navbar-brand" href="#">
   <%= image_tag("44px-Wiki_letter_w.svg.png", :class => "d-inline-block align-top", :title => "Whodabudda") %> 
    Whodabudda
  </a>
 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if current_page?(root_path) %>"><%= link_to 'Home', root_path, :class => 'nav-link' %></li>
            <li class="nav-item <%= 'active' if current_page?(welcome_about_path) %>"><%= link_to 'About', welcome_about_path, :class => 'nav-link' %></li>
            <li class="nav-item <%= 'active' if current_page?(welcome_doc_path) %>"><%= link_to 'Doc', welcome_doc_path, :class => 'nav-link' %></li>
            <li class="nav-item"> <%= link_to 'Account Options', '/user_options/' + current_user.id.to_s + '/edit',:class => 'nav-link' if user_signed_in? %></li>

            <% my_debug("session[:current_admin_id].nil?: " + session[:current_admin_id].nil?.to_s) %>
            <%# check_admin if user_signed_in? and session[:current_admin_id].nil?  %>
            <%# check_admin if session[:current_admin_id] > 0 and ! admin_signed_in? %>
            <% check_admin %>

            <li class="nav-item"> <%= link_to 'AuthAdmin', admin_session_path , :class => 'nav-link' if admin_need_login? %></li>

            <li class="nav-item"> <%= link_to 'ToggleAdminOn', utils_toggleAdmin_path(:setting => "true") , :class => 'nav-link' if admin_signed_in? and ! admin_on? %> </li>
            <li class="nav-item"> <%= link_to 'ToggleAdminOff', utils_toggleAdmin_path(:setting => "false") , :class => 'nav-link' if admin_signed_in? and admin_on? %> </li>

          <li class="nav-item btn-group">
               <a class="dropdown-toggle nav-link" href="#" type="button" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Filters 
                </a>
                <div class="dropdown-menu" role="menu" aria-labelledby="navbarDropdownMenuLink">
                    <%= link_to 'RantsOnly', welcome_toggleRantsOnly_path,:class => 'dropdown-item' %> 
                    <%= link_to 'MyComments', welcome_myCommentsOnly_path,:class => 'dropdown-item' if user_signed_in? %> 
                    <%= link_to 'Off', welcome_filtersOff_path,:class => 'dropdown-item' %> 
                </div>
            </li> 

            <li class="nav-item"> <%= link_to 'Log Off User', destroy_user_session_path , method: :delete , :class => 'nav-link'if user_signed_in? and ! admin_signed_in? %></li>
            <li class="nav-item"> <%= link_to 'Account', edit_user_registration_path , :class => 'nav-link' if user_signed_in? and ! admin_signed_in? %></li>
            <li class="nav-item"> <%= link_to 'Log Off Admin', destroy_admin_session_path , method: :delete , :class => 'nav-link'if admin_signed_in? %></li>
            <% if admin_on? %>
          <li class="nav-item btn-group">
               <a class="dropdown-toggle nav-link" href="#" type="button" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                New Content
                </a>
                <div class="dropdown-menu" role="menu" aria-labelledby="navbarDropdownMenuLink">
                    <%= link_to 'New Article',  [:new ,"commentable_content".underscore ],"data-turbolinks" => false, :class => "dropdown-item"  %>
                    <%#= link_to 'New Current Event',  [:new ,"current_event".underscore ], "data-turbolinks" => false, :class => "dropdown-item"  %>
                    <%#= link_to 'New Truth In Media', [:new ,"truth_in_media".underscore ],"data-turbolinks" => false, :class => "dropdown-item"  %>
            </div></li> 
            <% end %>
          </ul>
            <ul class="navbar-nav">
           <li class="nav-item"> 
              <%= session_message %>
           </li>
          </ul>
 
  </div>
</nav>


app/views/shared/navbar/_navbar_test.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">
   <%= image_tag("44px-Wiki_letter_w.svg.png", :class => "d-inline-block align-top", :title => "Whodabudda") %> 
    Whodabudda
  </a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if current_page?(root_path) %>"><%= link_to 'Home', root_path, :class => 'nav-link' %></li>
            <li class="nav-item <%= 'active' if current_page?(welcome_about_path) %>"><%= link_to 'About', welcome_about_path, :class => 'nav-link' %></li>
            <li class="nav-item <%= 'active' if current_page?(welcome_doc_path) %>"><%= link_to 'Doc', welcome_doc_path, :class => 'nav-link' %></li>

            <% my_debug("session[:current_admin_id].nil?: " + session[:current_admin_id].nil?.to_s) %>
            <% check_admin if user_signed_in? and session[:current_admin_id].nil?  %>

            <li class="nav-item"> <%= link_to 'AuthAdmin', admin_session_path , :class => 'nav-link' if admin_need_login? %></li>

            <li class="nav-item"> <%= link_to 'ToggleAdminOn', utils_toggleAdmin_path(:setting => "true") , :class => 'nav-link' if admin_signed_in? and ! admin_on? %> </li>
            <li class="nav-item"> <%= link_to 'ToggleAdminOff', utils_toggleAdmin_path(:setting => "false") , :class => 'nav-link' if admin_signed_in? and admin_on? %> </li>
            <%# if admin_signed_in? and !admin_on?? %>
            <%#end%>

            <li class="nav-item"> <%= link_to 'Log Off User', destroy_user_session_path , method: :delete , :class => 'nav-link'if user_signed_in? %></li>
            <li class="nav-item"> <%= link_to 'Log Off Admin', destroy_admin_session_path , method: :delete , :class => 'nav-link'if admin_signed_in? %></li>
       </ul>
    <ul class="navbar-nav">
           <li class="nav-item"> 
              <%= session_message %>
           </li>
    </ul>
  </div>
</nav>
<% 
=begin
    <div class="container-fluid">
            ☰
<nav class="navbar navbar-dark bg-primary"> 
<div class="container-fluid"> 
<button class="navbar-toggler hidden-md-up pull-right" type="button" data-toggle="collapse" data-target="#collapsingNavbar2"> ☰ 
</button> 
<a class="navbar-brand" href="#">Navbar sm</a> 
<div class="collapse navbar-toggleable-sm" id="collapsingNavbar2"> 
<ul class="nav navbar-nav"> 
<li class="nav-item"> 
<a class="nav-link" href="#">Link</a> 
</li> 
<li class="nav-item"> <a class="nav-link" href="#">Link</a> 
</li> 
</ul> 
<ul class="nav navbar-nav pull-xs-right"> 
<li class="nav-item"> <a class="nav-link" href="#">About</a> 
</li> 
</ul> 
</div> 
</div> 
</nav>
@media (max-width: 991px) {

  .navbar-header {
      float: none;
  }
  .navbar-left,.navbar-right {
      float: none !important;
  }
  .navbar-toggle {
      display: block;
  }
  .navbar-collapse {
      border-top: 1px solid transparent;
      box-shadow: inset 0 1px 0 rgba(255,255,255,0.1);
  }
  .navbar-fixed-top {
      top: 0;
      border-width: 0 0 1px;
  }
  .navbar-collapse.collapse {
      display: none!important;
  }
  .navbar-nav {
      float: none!important;
      margin-top: 7.5px;
  }
  .navbar-nav>li {
      float: none;
  }
  .navbar-nav>li>a {
      padding-top: 10px;
      padding-bottom: 10px;
  }
  .collapse.in{
      display:block !important;
  }
}
=end 
%>